#Plasmo Voice Changer preset
#Tue Oct 06 20:48:25 CEST 2026
autotuneKey=0.0
autotuneMix=0.0
autotuneScale=0.0
autotuneStrength=0.6
bitDepth=16.0
contributedVoiceId=
deEss=0.25
distortion=0.0
enabled=true
formant=0.87
gain=1.16
gate=0.3
growl=0.16
highEq=-2.0
lowEq=3.0
midEq=-0.5
mix=1.0
noise=0.0
pitch=0.84
preset=MAN
radio=0.0
reverbDecay=0.5
reverbMix=0.0
reverbSize=0.4
robotFrequency=60.0
robotMix=0.0
savedPresetName=
selfListen=false
strength=100
tremoloDepth=0.0
tremoloRate=2.5
voiceMatch=0.6
